# Generated by Django 4.1 on 2023-10-19 12:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('proprietario', models.CharField(max_length=200)),
                ('CNPJ', models.CharField(blank=True, max_length=20, null=True)),
                ('CPF', models.CharField(blank=True, max_length=20, null=True)),
                ('RG', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.PositiveBigIntegerField(blank=True, help_text='DD-9XXXX XXXX sem os espaços', null=True, unique=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('calibracao', models.DateField()),
                ('numero_serie', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Finalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(choices=[('1', 'Inspeção'), ('2', 'Manutenção'), ('3', 'Reparo'), ('4', 'Reforma'), ('5', 'Verificao metrológica')], default='1', help_text='Finalidade Descontaminação', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoTransportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
                ('numero_onu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('numero_compartimentos', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioDescontaminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('processo_descontaminacao', models.CharField(choices=[('1', 'Com ventilação forçada'), ('2', 'Com Aplicação de Vapor'), ('3', 'Com exaustão'), ('4', 'Com lavagem química'), ('5', 'Com lavagem com água')], help_text='Processo de Descontaminação', max_length=100, null=True)),
                ('finalidade_descontaminacao_outros', models.CharField(max_length=50, null=True)),
                ('tipo_equipamento', models.CharField(choices=[('1', 'Caminhão'), ('2', 'Semirreboque'), ('3', 'Rebocado')], help_text='Tipo do Equipamento', max_length=10, null=True)),
                ('prazo_validade', models.IntegerField(default=0, help_text='Prazo Validade Descontaminação', null=True)),
                ('lacre', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=10, null=True)),
                ('numero_lacre', models.IntegerField(null=True)),
                ('observacoes', models.TextField(null=True)),
                ('finalidade_descontaminacao', models.ManyToManyField(to='relatorio.finalidade')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DadosCompartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compartimento', models.IntegerField(default=0)),
                ('volume', models.IntegerField()),
                ('numeroONU', models.IntegerField()),
                ('classe_risco', models.CharField(max_length=100)),
                ('pressao_vapor', models.CharField(default='NA', max_length=10)),
                ('tempo', models.IntegerField()),
                ('massa_vapor', models.CharField(default='NA', max_length=10)),
                ('volumeAr', models.IntegerField()),
                ('neutralizante', models.CharField(max_length=200)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relatorio.relatoriodescontaminacao')),
                ('ultimo_produto_transportado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio.produtotransportado', verbose_name='Produto Perigoso Transportado')),
            ],
        ),
    ]
