# Generated by Django 4.1 on 2023-10-06 18:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('proprietario', models.CharField(max_length=200)),
                ('CNPJ', models.CharField(blank=True, max_length=20, null=True)),
                ('CPF', models.CharField(blank=True, max_length=20, null=True)),
                ('RG', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.PositiveBigIntegerField(blank=True, help_text='DD-9XXXX XXXX sem os espaços', null=True, unique=True, validators=[django.core.validators.MaxValueValidator(99999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('calibracao', models.DateField()),
                ('numero_serie', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoTransportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('numero_compartilhamentos', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioDescontaminacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_relatorio', models.IntegerField(auto_created=True)),
                ('processo_descontaminacao', models.CharField(choices=[('1', 'Com ventilação forçada'), ('2', 'Com Aplicação de Vapor'), ('3', 'Com exaustão'), ('4', 'Com lavagem química'), ('5', 'Com lavagem com água')], help_text='Processo de Descontaminação', max_length=100)),
                ('finalidade_descontaminacao', models.CharField(choices=[('1', 'Inspeção'), ('2', 'Manunteção'), ('3', 'Reparo'), ('4', 'Reforma'), ('5', 'Verificao metrológica')], default='1', help_text='Finalidade Descontaminação', max_length=50)),
                ('finalidade_descontaminacao_outros', models.CharField(max_length=50)),
                ('tipo_equipamento', models.CharField(choices=[('TIPO A', 'TIPO A'), ('TIPO B', 'TIPO B')], help_text='Tipo do Equipamento', max_length=10)),
                ('prazo_validade', models.IntegerField(default=0, help_text='Prazo Validade Descontaminação')),
                ('lacre', models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=10)),
                ('numero_lacre', models.IntegerField()),
                ('observacoes', models.TextField()),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DadosCompartimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compartilhamento', models.IntegerField(default=0)),
                ('numeroONU', models.IntegerField()),
                ('classe_risco', models.CharField(max_length=100)),
                ('pressao_vapor', models.CharField(default='NA', max_length=10)),
                ('tempo', models.TimeField()),
                ('massa_vapor', models.CharField(default='NA', max_length=10)),
                ('volume', models.IntegerField()),
                ('neutralizante', models.CharField(default='NA', max_length=10)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio.relatoriodescontaminacao')),
                ('ultimo_produto_transportado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio.produtotransportado', verbose_name='Produto PerigosoTransportado')),
            ],
        ),
    ]
