# Generated by Django 4.1 on 2023-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='finalidade_descontaminacao',
            field=models.ManyToManyField(blank=True, null=True, to='relatorio.finalidade'),
        ),
    ]
