# Generated by Django 4.1 on 2023-10-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='finalidade_descontaminacao',
            field=models.CharField(choices=[('1', 'Inspeção'), ('2', 'Manunteção'), ('3', 'Reparo'), ('4', 'Reforma'), ('5', 'Verificao metrológica')], default='1', help_text='Finalidade Descontaminação', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='finalidade_descontaminacao_outros',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='lacre',
            field=models.CharField(choices=[('N', 'N'), ('S', 'S')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='numero_lacre',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='observacoes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='prazo_validade',
            field=models.IntegerField(default=0, help_text='Prazo Validade Descontaminação', null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='processo_descontaminacao',
            field=models.CharField(choices=[('1', 'Com ventilação forçada'), ('2', 'Com Aplicação de Vapor'), ('3', 'Com exaustão'), ('4', 'Com lavagem química'), ('5', 'Com lavagem com água')], help_text='Processo de Descontaminação', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='tipo_equipamento',
            field=models.CharField(choices=[('TIPO A', 'TIPO A'), ('TIPO B', 'TIPO B')], help_text='Tipo do Equipamento', max_length=10, null=True),
        ),
    ]
