# Generated by Django 4.1 on 2023-12-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_alter_relatoriodescontaminacao_finalidade_descontaminacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='numeroEquipamento',
            field=models.CharField(default='numero', max_length=30),
            preserve_default=False,
        ),
    ]
