# Generated by Django 4.1 on 2023-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0002_alter_relatoriodescontaminacao_finalidade_descontaminacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='numero_relatorio',
            field=models.IntegerField(auto_created=True, null=True),
        ),
    ]
