# Generated by Django 4.1 on 2023-10-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0003_alter_relatoriodescontaminacao_numero_relatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodescontaminacao',
            name='numero_relatorio',
        ),
    ]
