# Generated by Django 4.1 on 2023-12-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0004_remove_veiculo_numeroequipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='numeroEquipamento',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='numeroEquipamento',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
    ]
