# Generated by Django 4.1 on 2023-10-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0004_remove_relatoriodescontaminacao_numero_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtotransportado',
            name='numero_onu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
