# Generated by Django 4.1 on 2023-10-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0005_produtotransportado_numero_onu'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodescontaminacao',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='relatorio.cliente'),
            preserve_default=False,
        ),
    ]
