# Generated by Django 4.1 on 2023-12-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0005_remove_equipamento_numeroequipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='numero_serie',
        ),
    ]
