# Generated by Django 4.1 on 2023-10-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0006_relatoriodescontaminacao_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodescontaminacao',
            name='cliente',
        ),
    ]
