# Generated by Django 4.1 on 2023-12-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0006_remove_equipamento_numero_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
