# Generated by Django 4.1 on 2024-09-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0007_equipamento_numero_serie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CNPJ',
            new_name='documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='CPF',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='RG',
        ),
    ]
