# Generated by Django 4.1 on 2023-10-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0007_remove_relatoriodescontaminacao_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscompartimento',
            name='volumeAr',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadoscompartimento',
            name='neutralizante',
            field=models.CharField(max_length=200),
        ),
    ]
