# Generated by Django 4.1 on 2023-10-13 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0009_alter_dadoscompartimento_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatoriodescontaminacao',
            name='data',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
