# Generated by Django 4.1 on 2023-10-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0010_relatoriodescontaminacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadoscompartimento',
            old_name='numero_compartilhamento',
            new_name='numero_compartimento',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='numero_compartilhamentos',
            new_name='numero_compartimentos',
        ),
    ]
