# Generated by Django 4.1 on 2023-10-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0011_rename_numero_compartilhamento_dadoscompartimento_numero_compartimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriodescontaminacao',
            name='tipo_equipamento',
            field=models.CharField(choices=[('1', 'Caminhão'), ('2', 'Semirreboque'), ('3', 'Rebocado')], help_text='Tipo do Equipamento', max_length=10, null=True),
        ),
    ]
