# Generated by Django 4.1 on 2023-10-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0013_alter_dadoscompartimento_relatorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatoriodescontaminacao',
            name='veiculo',
        ),
        migrations.AddField(
            model_name='relatoriodescontaminacao',
            name='veiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='relatorio.veiculo'),
            preserve_default=False,
        ),
    ]
