# Generated by Django 4.1 on 2023-10-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio', '0015_finalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalidade',
            name='finalidade',
            field=models.CharField(choices=[('1', 'Inspeção'), ('2', 'Manutenção'), ('3', 'Reparo'), ('4', 'Reforma'), ('5', 'Verificao metrológica')], default='1', help_text='Finalidade Descontaminação', max_length=50, null=True),
        ),
    ]
